### PR TITLE
Initial website based on lfortran.org

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**

### CODE REVIEW

**Comment by Shaikh-Ubaid** [comment]
@certik please review/approve. I guess we can merge this and work upon improvements in successive PRs. Let us get to build the blog site first and then work on refining the wordings/description used in the lpython.org website.

**Comment by Shaikh-Ubaid** [comment]
I think we can probably have the sources and built files in this same repository under different branches (`main` and `gh-pages` respectively) similar to as we have for https://github.com/lfortran/lcompilers_frontend. I will be sending another PR updating the CI to accomplish this. Please let me know if this would be fine.

**Comment by Shaikh-Ubaid** [comment]
For Later:
- [ ] Google Analytics Id to be added (currently it is empty string)
- [ ] Urls to design and documentation are currently from LFortran
- [ ] Twitter link of `lfortran.org` currently used
- [ ] Releases section in the `layouts/download/downloadlayout.html` is to be updated
- [ ] Make the site work

**Comment by certik** [comment]
Ok, let's merge it and iterate on this until it's ready to announce tomorrow.

**Comment by Shaikh-Ubaid** [comment]
Thank you so much @certik!

**Pull request merged**
